
export const metadata = {
  title: "about us - BoltUI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <> 
        {children}
    </>
  );
}
